<?php
namespace Workabox\API;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class CalculateOrderInfo
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'Order',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\CustomerOrder',
        ),
        2 => array(
            'var' => 'MIBarCodes',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        3 => array(
            'var' => 'Messages',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        4 => array(
            'var' => 'SaveOrder',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var \Workabox\API\CustomerOrder
     */
    public $Order = null;
    /**
     * @var string[]
     */
    public $MIBarCodes = null;
    /**
     * @var string[]
     */
    public $Messages = null;
    /**
     * @var bool
     */
    public $SaveOrder = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['Order'])) {
                $this->Order = $vals['Order'];
            }
            if (isset($vals['MIBarCodes'])) {
                $this->MIBarCodes = $vals['MIBarCodes'];
            }
            if (isset($vals['Messages'])) {
                $this->Messages = $vals['Messages'];
            }
            if (isset($vals['SaveOrder'])) {
                $this->SaveOrder = $vals['SaveOrder'];
            }
        }
    }

    public function getName()
    {
        return 'CalculateOrderInfo';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->Order = new \Workabox\API\CustomerOrder();
                        $xfer += $this->Order->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::LST) {
                        $this->MIBarCodes = array();
                        $_size1050 = 0;
                        $_etype1053 = 0;
                        $xfer += $input->readListBegin($_etype1053, $_size1050);
                        for ($_i1054 = 0; $_i1054 < $_size1050; ++$_i1054) {
                            $elem1055 = null;
                            $xfer += $input->readString($elem1055);
                            $this->MIBarCodes []= $elem1055;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::LST) {
                        $this->Messages = array();
                        $_size1056 = 0;
                        $_etype1059 = 0;
                        $xfer += $input->readListBegin($_etype1059, $_size1056);
                        for ($_i1060 = 0; $_i1060 < $_size1056; ++$_i1060) {
                            $elem1061 = null;
                            $xfer += $input->readString($elem1061);
                            $this->Messages []= $elem1061;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->SaveOrder);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('CalculateOrderInfo');
        if ($this->Order !== null) {
            if (!is_object($this->Order)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Order', TType::STRUCT, 1);
            $xfer += $this->Order->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->MIBarCodes !== null) {
            if (!is_array($this->MIBarCodes)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('MIBarCodes', TType::LST, 2);
            $output->writeListBegin(TType::STRING, count($this->MIBarCodes));
            foreach ($this->MIBarCodes as $iter1062) {
                $xfer += $output->writeString($iter1062);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Messages !== null) {
            if (!is_array($this->Messages)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Messages', TType::LST, 3);
            $output->writeListBegin(TType::STRING, count($this->Messages));
            foreach ($this->Messages as $iter1063) {
                $xfer += $output->writeString($iter1063);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->SaveOrder !== null) {
            $xfer += $output->writeFieldBegin('SaveOrder', TType::BOOL, 4);
            $xfer += $output->writeBool($this->SaveOrder);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
