<?php
namespace Workabox\API;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class CashDeskRTT
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'ID',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'OuterID',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'ErrorMessage',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'ObjectName',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'FPNumber',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'CashZeroTime',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        7 => array(
            'var' => 'ECRType',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        8 => array(
            'var' => 'ECRIP',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        9 => array(
            'var' => 'SyncSuccessDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        10 => array(
            'var' => 'SyncTryDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        11 => array(
            'var' => 'SyncResult',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        12 => array(
            'var' => 'IsFranchising',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        13 => array(
            'var' => 'HierarchyBranch',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        14 => array(
            'var' => 'ObjectOwner',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        15 => array(
            'var' => 'OuterCodes',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Workabox\API\OuterCodesLine',
                ),
        ),
        16 => array(
            'var' => 'StateMain',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        17 => array(
            'var' => 'CashDescInRTTMaster',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
    );

    /**
     * @var int
     */
    public $ID = null;
    /**
     * @var string
     */
    public $OuterID = null;
    /**
     * @var string
     */
    public $ErrorMessage = null;
    /**
     * @var string
     */
    public $ObjectName = null;
    /**
     * @var string
     */
    public $FPNumber = null;
    /**
     * @var string
     */
    public $CashZeroTime = null;
    /**
     * @var int
     */
    public $ECRType = null;
    /**
     * @var string
     */
    public $ECRIP = null;
    /**
     * @var string
     */
    public $SyncSuccessDate = null;
    /**
     * @var string
     */
    public $SyncTryDate = null;
    /**
     * @var bool
     */
    public $SyncResult = null;
    /**
     * @var bool
     */
    public $IsFranchising = null;
    /**
     * @var string
     */
    public $HierarchyBranch = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $ObjectOwner = null;
    /**
     * @var \Workabox\API\OuterCodesLine[]
     */
    public $OuterCodes = null;
    /**
     * @var string
     */
    public $StateMain = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $CashDescInRTTMaster = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['ID'])) {
                $this->ID = $vals['ID'];
            }
            if (isset($vals['OuterID'])) {
                $this->OuterID = $vals['OuterID'];
            }
            if (isset($vals['ErrorMessage'])) {
                $this->ErrorMessage = $vals['ErrorMessage'];
            }
            if (isset($vals['ObjectName'])) {
                $this->ObjectName = $vals['ObjectName'];
            }
            if (isset($vals['FPNumber'])) {
                $this->FPNumber = $vals['FPNumber'];
            }
            if (isset($vals['CashZeroTime'])) {
                $this->CashZeroTime = $vals['CashZeroTime'];
            }
            if (isset($vals['ECRType'])) {
                $this->ECRType = $vals['ECRType'];
            }
            if (isset($vals['ECRIP'])) {
                $this->ECRIP = $vals['ECRIP'];
            }
            if (isset($vals['SyncSuccessDate'])) {
                $this->SyncSuccessDate = $vals['SyncSuccessDate'];
            }
            if (isset($vals['SyncTryDate'])) {
                $this->SyncTryDate = $vals['SyncTryDate'];
            }
            if (isset($vals['SyncResult'])) {
                $this->SyncResult = $vals['SyncResult'];
            }
            if (isset($vals['IsFranchising'])) {
                $this->IsFranchising = $vals['IsFranchising'];
            }
            if (isset($vals['HierarchyBranch'])) {
                $this->HierarchyBranch = $vals['HierarchyBranch'];
            }
            if (isset($vals['ObjectOwner'])) {
                $this->ObjectOwner = $vals['ObjectOwner'];
            }
            if (isset($vals['OuterCodes'])) {
                $this->OuterCodes = $vals['OuterCodes'];
            }
            if (isset($vals['StateMain'])) {
                $this->StateMain = $vals['StateMain'];
            }
            if (isset($vals['CashDescInRTTMaster'])) {
                $this->CashDescInRTTMaster = $vals['CashDescInRTTMaster'];
            }
        }
    }

    public function getName()
    {
        return 'CashDeskRTT';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->ID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->OuterID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ErrorMessage);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ObjectName);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->FPNumber);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->CashZeroTime);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->ECRType);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ECRIP);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 9:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->SyncSuccessDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->SyncTryDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->SyncResult);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->IsFranchising);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->HierarchyBranch);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 14:
                    if ($ftype == TType::STRUCT) {
                        $this->ObjectOwner = new \Workabox\API\ObjectID();
                        $xfer += $this->ObjectOwner->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 15:
                    if ($ftype == TType::LST) {
                        $this->OuterCodes = array();
                        $_size413 = 0;
                        $_etype416 = 0;
                        $xfer += $input->readListBegin($_etype416, $_size413);
                        for ($_i417 = 0; $_i417 < $_size413; ++$_i417) {
                            $elem418 = null;
                            $elem418 = new \Workabox\API\OuterCodesLine();
                            $xfer += $elem418->read($input);
                            $this->OuterCodes []= $elem418;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 16:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->StateMain);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 17:
                    if ($ftype == TType::STRUCT) {
                        $this->CashDescInRTTMaster = new \Workabox\API\ObjectID();
                        $xfer += $this->CashDescInRTTMaster->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('CashDeskRTT');
        if ($this->ID !== null) {
            $xfer += $output->writeFieldBegin('ID', TType::I32, 1);
            $xfer += $output->writeI32($this->ID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterID !== null) {
            $xfer += $output->writeFieldBegin('OuterID', TType::STRING, 2);
            $xfer += $output->writeString($this->OuterID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ErrorMessage !== null) {
            $xfer += $output->writeFieldBegin('ErrorMessage', TType::STRING, 3);
            $xfer += $output->writeString($this->ErrorMessage);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ObjectName !== null) {
            $xfer += $output->writeFieldBegin('ObjectName', TType::STRING, 4);
            $xfer += $output->writeString($this->ObjectName);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->FPNumber !== null) {
            $xfer += $output->writeFieldBegin('FPNumber', TType::STRING, 5);
            $xfer += $output->writeString($this->FPNumber);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->CashZeroTime !== null) {
            $xfer += $output->writeFieldBegin('CashZeroTime', TType::STRING, 6);
            $xfer += $output->writeString($this->CashZeroTime);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ECRType !== null) {
            $xfer += $output->writeFieldBegin('ECRType', TType::I32, 7);
            $xfer += $output->writeI32($this->ECRType);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ECRIP !== null) {
            $xfer += $output->writeFieldBegin('ECRIP', TType::STRING, 8);
            $xfer += $output->writeString($this->ECRIP);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->SyncSuccessDate !== null) {
            $xfer += $output->writeFieldBegin('SyncSuccessDate', TType::STRING, 9);
            $xfer += $output->writeString($this->SyncSuccessDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->SyncTryDate !== null) {
            $xfer += $output->writeFieldBegin('SyncTryDate', TType::STRING, 10);
            $xfer += $output->writeString($this->SyncTryDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->SyncResult !== null) {
            $xfer += $output->writeFieldBegin('SyncResult', TType::BOOL, 11);
            $xfer += $output->writeBool($this->SyncResult);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->IsFranchising !== null) {
            $xfer += $output->writeFieldBegin('IsFranchising', TType::BOOL, 12);
            $xfer += $output->writeBool($this->IsFranchising);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->HierarchyBranch !== null) {
            $xfer += $output->writeFieldBegin('HierarchyBranch', TType::STRING, 13);
            $xfer += $output->writeString($this->HierarchyBranch);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ObjectOwner !== null) {
            if (!is_object($this->ObjectOwner)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('ObjectOwner', TType::STRUCT, 14);
            $xfer += $this->ObjectOwner->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterCodes !== null) {
            if (!is_array($this->OuterCodes)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('OuterCodes', TType::LST, 15);
            $output->writeListBegin(TType::STRUCT, count($this->OuterCodes));
            foreach ($this->OuterCodes as $iter419) {
                $xfer += $iter419->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->StateMain !== null) {
            $xfer += $output->writeFieldBegin('StateMain', TType::STRING, 16);
            $xfer += $output->writeString($this->StateMain);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->CashDescInRTTMaster !== null) {
            if (!is_object($this->CashDescInRTTMaster)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('CashDescInRTTMaster', TType::STRUCT, 17);
            $xfer += $this->CashDescInRTTMaster->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
