<?php
namespace Workabox\API;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class CustomerOrder
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'ID',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'OuterID',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'ShippingDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'MarketingDiscount',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        5 => array(
            'var' => 'AppliedMI',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Workabox\API\AppliedMILine',
                ),
        ),
        6 => array(
            'var' => 'GoodsInRetailSale',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Workabox\API\GoodsInRetailSaleLine',
                ),
        ),
        7 => array(
            'var' => 'RTT',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        8 => array(
            'var' => 'Client',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        9 => array(
            'var' => 'SpecialDiscount',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        10 => array(
            'var' => 'ManagerDiscount',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        11 => array(
            'var' => 'ExtendedDiscount',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        12 => array(
            'var' => 'Cashier',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        13 => array(
            'var' => 'PrePay',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        14 => array(
            'var' => 'Additional',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        15 => array(
            'var' => 'DocumentSumm',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        16 => array(
            'var' => 'GUID',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        17 => array(
            'var' => 'DocNumber',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        18 => array(
            'var' => 'DocumentDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        19 => array(
            'var' => 'OuterCodes',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Workabox\API\OuterCodesLine',
                ),
        ),
        20 => array(
            'var' => 'StateOrderCustomer',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $ID = null;
    /**
     * @var string
     */
    public $OuterID = null;
    /**
     * @var string
     */
    public $ShippingDate = null;
    /**
     * @var double
     */
    public $MarketingDiscount = null;
    /**
     * @var \Workabox\API\AppliedMILine[]
     */
    public $AppliedMI = null;
    /**
     * @var \Workabox\API\GoodsInRetailSaleLine[]
     */
    public $GoodsInRetailSale = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $RTT = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $Client = null;
    /**
     * @var double
     */
    public $SpecialDiscount = null;
    /**
     * @var double
     */
    public $ManagerDiscount = null;
    /**
     * @var double
     */
    public $ExtendedDiscount = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $Cashier = null;
    /**
     * @var double
     */
    public $PrePay = null;
    /**
     * @var string
     */
    public $Additional = null;
    /**
     * @var double
     */
    public $DocumentSumm = null;
    /**
     * @var string
     */
    public $GUID = null;
    /**
     * @var string
     */
    public $DocNumber = null;
    /**
     * @var string
     */
    public $DocumentDate = null;
    /**
     * @var \Workabox\API\OuterCodesLine[]
     */
    public $OuterCodes = null;
    /**
     * @var string
     */
    public $StateOrderCustomer = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['ID'])) {
                $this->ID = $vals['ID'];
            }
            if (isset($vals['OuterID'])) {
                $this->OuterID = $vals['OuterID'];
            }
            if (isset($vals['ShippingDate'])) {
                $this->ShippingDate = $vals['ShippingDate'];
            }
            if (isset($vals['MarketingDiscount'])) {
                $this->MarketingDiscount = $vals['MarketingDiscount'];
            }
            if (isset($vals['AppliedMI'])) {
                $this->AppliedMI = $vals['AppliedMI'];
            }
            if (isset($vals['GoodsInRetailSale'])) {
                $this->GoodsInRetailSale = $vals['GoodsInRetailSale'];
            }
            if (isset($vals['RTT'])) {
                $this->RTT = $vals['RTT'];
            }
            if (isset($vals['Client'])) {
                $this->Client = $vals['Client'];
            }
            if (isset($vals['SpecialDiscount'])) {
                $this->SpecialDiscount = $vals['SpecialDiscount'];
            }
            if (isset($vals['ManagerDiscount'])) {
                $this->ManagerDiscount = $vals['ManagerDiscount'];
            }
            if (isset($vals['ExtendedDiscount'])) {
                $this->ExtendedDiscount = $vals['ExtendedDiscount'];
            }
            if (isset($vals['Cashier'])) {
                $this->Cashier = $vals['Cashier'];
            }
            if (isset($vals['PrePay'])) {
                $this->PrePay = $vals['PrePay'];
            }
            if (isset($vals['Additional'])) {
                $this->Additional = $vals['Additional'];
            }
            if (isset($vals['DocumentSumm'])) {
                $this->DocumentSumm = $vals['DocumentSumm'];
            }
            if (isset($vals['GUID'])) {
                $this->GUID = $vals['GUID'];
            }
            if (isset($vals['DocNumber'])) {
                $this->DocNumber = $vals['DocNumber'];
            }
            if (isset($vals['DocumentDate'])) {
                $this->DocumentDate = $vals['DocumentDate'];
            }
            if (isset($vals['OuterCodes'])) {
                $this->OuterCodes = $vals['OuterCodes'];
            }
            if (isset($vals['StateOrderCustomer'])) {
                $this->StateOrderCustomer = $vals['StateOrderCustomer'];
            }
        }
    }

    public function getName()
    {
        return 'CustomerOrder';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->ID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->OuterID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ShippingDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->MarketingDiscount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::LST) {
                        $this->AppliedMI = array();
                        $_size756 = 0;
                        $_etype759 = 0;
                        $xfer += $input->readListBegin($_etype759, $_size756);
                        for ($_i760 = 0; $_i760 < $_size756; ++$_i760) {
                            $elem761 = null;
                            $elem761 = new \Workabox\API\AppliedMILine();
                            $xfer += $elem761->read($input);
                            $this->AppliedMI []= $elem761;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::LST) {
                        $this->GoodsInRetailSale = array();
                        $_size762 = 0;
                        $_etype765 = 0;
                        $xfer += $input->readListBegin($_etype765, $_size762);
                        for ($_i766 = 0; $_i766 < $_size762; ++$_i766) {
                            $elem767 = null;
                            $elem767 = new \Workabox\API\GoodsInRetailSaleLine();
                            $xfer += $elem767->read($input);
                            $this->GoodsInRetailSale []= $elem767;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::STRUCT) {
                        $this->RTT = new \Workabox\API\ObjectID();
                        $xfer += $this->RTT->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::STRUCT) {
                        $this->Client = new \Workabox\API\ObjectID();
                        $xfer += $this->Client->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 9:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->SpecialDiscount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->ManagerDiscount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->ExtendedDiscount);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::STRUCT) {
                        $this->Cashier = new \Workabox\API\ObjectID();
                        $xfer += $this->Cashier->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->PrePay);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 14:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Additional);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 15:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->DocumentSumm);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 16:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->GUID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 17:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocNumber);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 18:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocumentDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 19:
                    if ($ftype == TType::LST) {
                        $this->OuterCodes = array();
                        $_size768 = 0;
                        $_etype771 = 0;
                        $xfer += $input->readListBegin($_etype771, $_size768);
                        for ($_i772 = 0; $_i772 < $_size768; ++$_i772) {
                            $elem773 = null;
                            $elem773 = new \Workabox\API\OuterCodesLine();
                            $xfer += $elem773->read($input);
                            $this->OuterCodes []= $elem773;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 20:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->StateOrderCustomer);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('CustomerOrder');
        if ($this->ID !== null) {
            $xfer += $output->writeFieldBegin('ID', TType::I32, 1);
            $xfer += $output->writeI32($this->ID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterID !== null) {
            $xfer += $output->writeFieldBegin('OuterID', TType::STRING, 2);
            $xfer += $output->writeString($this->OuterID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ShippingDate !== null) {
            $xfer += $output->writeFieldBegin('ShippingDate', TType::STRING, 3);
            $xfer += $output->writeString($this->ShippingDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->MarketingDiscount !== null) {
            $xfer += $output->writeFieldBegin('MarketingDiscount', TType::DOUBLE, 4);
            $xfer += $output->writeDouble($this->MarketingDiscount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->AppliedMI !== null) {
            if (!is_array($this->AppliedMI)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('AppliedMI', TType::LST, 5);
            $output->writeListBegin(TType::STRUCT, count($this->AppliedMI));
            foreach ($this->AppliedMI as $iter774) {
                $xfer += $iter774->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->GoodsInRetailSale !== null) {
            if (!is_array($this->GoodsInRetailSale)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('GoodsInRetailSale', TType::LST, 6);
            $output->writeListBegin(TType::STRUCT, count($this->GoodsInRetailSale));
            foreach ($this->GoodsInRetailSale as $iter775) {
                $xfer += $iter775->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->RTT !== null) {
            if (!is_object($this->RTT)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('RTT', TType::STRUCT, 7);
            $xfer += $this->RTT->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Client !== null) {
            if (!is_object($this->Client)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Client', TType::STRUCT, 8);
            $xfer += $this->Client->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->SpecialDiscount !== null) {
            $xfer += $output->writeFieldBegin('SpecialDiscount', TType::DOUBLE, 9);
            $xfer += $output->writeDouble($this->SpecialDiscount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ManagerDiscount !== null) {
            $xfer += $output->writeFieldBegin('ManagerDiscount', TType::DOUBLE, 10);
            $xfer += $output->writeDouble($this->ManagerDiscount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ExtendedDiscount !== null) {
            $xfer += $output->writeFieldBegin('ExtendedDiscount', TType::DOUBLE, 11);
            $xfer += $output->writeDouble($this->ExtendedDiscount);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Cashier !== null) {
            if (!is_object($this->Cashier)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Cashier', TType::STRUCT, 12);
            $xfer += $this->Cashier->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->PrePay !== null) {
            $xfer += $output->writeFieldBegin('PrePay', TType::DOUBLE, 13);
            $xfer += $output->writeDouble($this->PrePay);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Additional !== null) {
            $xfer += $output->writeFieldBegin('Additional', TType::STRING, 14);
            $xfer += $output->writeString($this->Additional);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocumentSumm !== null) {
            $xfer += $output->writeFieldBegin('DocumentSumm', TType::DOUBLE, 15);
            $xfer += $output->writeDouble($this->DocumentSumm);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->GUID !== null) {
            $xfer += $output->writeFieldBegin('GUID', TType::STRING, 16);
            $xfer += $output->writeString($this->GUID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocNumber !== null) {
            $xfer += $output->writeFieldBegin('DocNumber', TType::STRING, 17);
            $xfer += $output->writeString($this->DocNumber);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocumentDate !== null) {
            $xfer += $output->writeFieldBegin('DocumentDate', TType::STRING, 18);
            $xfer += $output->writeString($this->DocumentDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterCodes !== null) {
            if (!is_array($this->OuterCodes)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('OuterCodes', TType::LST, 19);
            $output->writeListBegin(TType::STRUCT, count($this->OuterCodes));
            foreach ($this->OuterCodes as $iter776) {
                $xfer += $iter776->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->StateOrderCustomer !== null) {
            $xfer += $output->writeFieldBegin('StateOrderCustomer', TType::STRING, 20);
            $xfer += $output->writeString($this->StateOrderCustomer);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
