<?php
namespace Workabox\API;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class DataTypes
{
    const StringType = 0;

    const NumericType = 1;

    const Numeric2Type = 2;

    const Numeric3Type = 3;

    const SystemEnumType = 4;

    const DateType = 5;

    const TextType = 6;

    const Catalog = 7;

    static public $__names = array(
        0 => 'StringType',
        1 => 'NumericType',
        2 => 'Numeric2Type',
        3 => 'Numeric3Type',
        4 => 'SystemEnumType',
        5 => 'DateType',
        6 => 'TextType',
        7 => 'Catalog',
    );
}

