<?php
namespace Workabox\API;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MoneyMovementInner
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'ID',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'OuterID',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'ResponsibleSender',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        4 => array(
            'var' => 'ResponsibleReceiver',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        5 => array(
            'var' => 'PayDetails',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'MoneyMovementInnerSender',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        7 => array(
            'var' => 'MoneyMovementInnerReceiver',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        8 => array(
            'var' => 'SenderMoneyStorage',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        9 => array(
            'var' => 'ReceiverMoneyStorage',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        10 => array(
            'var' => 'Additional',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        11 => array(
            'var' => 'DocumentSumm',
            'isRequired' => false,
            'type' => TType::DOUBLE,
        ),
        12 => array(
            'var' => 'GUID',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        13 => array(
            'var' => 'DocNumber',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        14 => array(
            'var' => 'DocumentDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        15 => array(
            'var' => 'OuterCodes',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Workabox\API\OuterCodesLine',
                ),
        ),
        16 => array(
            'var' => 'StateMoney',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var int
     */
    public $ID = null;
    /**
     * @var string
     */
    public $OuterID = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $ResponsibleSender = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $ResponsibleReceiver = null;
    /**
     * @var string
     */
    public $PayDetails = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $MoneyMovementInnerSender = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $MoneyMovementInnerReceiver = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $SenderMoneyStorage = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $ReceiverMoneyStorage = null;
    /**
     * @var string
     */
    public $Additional = null;
    /**
     * @var double
     */
    public $DocumentSumm = null;
    /**
     * @var string
     */
    public $GUID = null;
    /**
     * @var string
     */
    public $DocNumber = null;
    /**
     * @var string
     */
    public $DocumentDate = null;
    /**
     * @var \Workabox\API\OuterCodesLine[]
     */
    public $OuterCodes = null;
    /**
     * @var string
     */
    public $StateMoney = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['ID'])) {
                $this->ID = $vals['ID'];
            }
            if (isset($vals['OuterID'])) {
                $this->OuterID = $vals['OuterID'];
            }
            if (isset($vals['ResponsibleSender'])) {
                $this->ResponsibleSender = $vals['ResponsibleSender'];
            }
            if (isset($vals['ResponsibleReceiver'])) {
                $this->ResponsibleReceiver = $vals['ResponsibleReceiver'];
            }
            if (isset($vals['PayDetails'])) {
                $this->PayDetails = $vals['PayDetails'];
            }
            if (isset($vals['MoneyMovementInnerSender'])) {
                $this->MoneyMovementInnerSender = $vals['MoneyMovementInnerSender'];
            }
            if (isset($vals['MoneyMovementInnerReceiver'])) {
                $this->MoneyMovementInnerReceiver = $vals['MoneyMovementInnerReceiver'];
            }
            if (isset($vals['SenderMoneyStorage'])) {
                $this->SenderMoneyStorage = $vals['SenderMoneyStorage'];
            }
            if (isset($vals['ReceiverMoneyStorage'])) {
                $this->ReceiverMoneyStorage = $vals['ReceiverMoneyStorage'];
            }
            if (isset($vals['Additional'])) {
                $this->Additional = $vals['Additional'];
            }
            if (isset($vals['DocumentSumm'])) {
                $this->DocumentSumm = $vals['DocumentSumm'];
            }
            if (isset($vals['GUID'])) {
                $this->GUID = $vals['GUID'];
            }
            if (isset($vals['DocNumber'])) {
                $this->DocNumber = $vals['DocNumber'];
            }
            if (isset($vals['DocumentDate'])) {
                $this->DocumentDate = $vals['DocumentDate'];
            }
            if (isset($vals['OuterCodes'])) {
                $this->OuterCodes = $vals['OuterCodes'];
            }
            if (isset($vals['StateMoney'])) {
                $this->StateMoney = $vals['StateMoney'];
            }
        }
    }

    public function getName()
    {
        return 'MoneyMovementInner';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->ID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->OuterID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRUCT) {
                        $this->ResponsibleSender = new \Workabox\API\ObjectID();
                        $xfer += $this->ResponsibleSender->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRUCT) {
                        $this->ResponsibleReceiver = new \Workabox\API\ObjectID();
                        $xfer += $this->ResponsibleReceiver->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->PayDetails);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::STRUCT) {
                        $this->MoneyMovementInnerSender = new \Workabox\API\ObjectID();
                        $xfer += $this->MoneyMovementInnerSender->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::STRUCT) {
                        $this->MoneyMovementInnerReceiver = new \Workabox\API\ObjectID();
                        $xfer += $this->MoneyMovementInnerReceiver->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::STRUCT) {
                        $this->SenderMoneyStorage = new \Workabox\API\ObjectID();
                        $xfer += $this->SenderMoneyStorage->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 9:
                    if ($ftype == TType::STRUCT) {
                        $this->ReceiverMoneyStorage = new \Workabox\API\ObjectID();
                        $xfer += $this->ReceiverMoneyStorage->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Additional);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::DOUBLE) {
                        $xfer += $input->readDouble($this->DocumentSumm);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->GUID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocNumber);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 14:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocumentDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 15:
                    if ($ftype == TType::LST) {
                        $this->OuterCodes = array();
                        $_size903 = 0;
                        $_etype906 = 0;
                        $xfer += $input->readListBegin($_etype906, $_size903);
                        for ($_i907 = 0; $_i907 < $_size903; ++$_i907) {
                            $elem908 = null;
                            $elem908 = new \Workabox\API\OuterCodesLine();
                            $xfer += $elem908->read($input);
                            $this->OuterCodes []= $elem908;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 16:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->StateMoney);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MoneyMovementInner');
        if ($this->ID !== null) {
            $xfer += $output->writeFieldBegin('ID', TType::I32, 1);
            $xfer += $output->writeI32($this->ID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterID !== null) {
            $xfer += $output->writeFieldBegin('OuterID', TType::STRING, 2);
            $xfer += $output->writeString($this->OuterID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ResponsibleSender !== null) {
            if (!is_object($this->ResponsibleSender)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('ResponsibleSender', TType::STRUCT, 3);
            $xfer += $this->ResponsibleSender->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ResponsibleReceiver !== null) {
            if (!is_object($this->ResponsibleReceiver)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('ResponsibleReceiver', TType::STRUCT, 4);
            $xfer += $this->ResponsibleReceiver->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->PayDetails !== null) {
            $xfer += $output->writeFieldBegin('PayDetails', TType::STRING, 5);
            $xfer += $output->writeString($this->PayDetails);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->MoneyMovementInnerSender !== null) {
            if (!is_object($this->MoneyMovementInnerSender)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('MoneyMovementInnerSender', TType::STRUCT, 6);
            $xfer += $this->MoneyMovementInnerSender->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->MoneyMovementInnerReceiver !== null) {
            if (!is_object($this->MoneyMovementInnerReceiver)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('MoneyMovementInnerReceiver', TType::STRUCT, 7);
            $xfer += $this->MoneyMovementInnerReceiver->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->SenderMoneyStorage !== null) {
            if (!is_object($this->SenderMoneyStorage)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('SenderMoneyStorage', TType::STRUCT, 8);
            $xfer += $this->SenderMoneyStorage->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ReceiverMoneyStorage !== null) {
            if (!is_object($this->ReceiverMoneyStorage)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('ReceiverMoneyStorage', TType::STRUCT, 9);
            $xfer += $this->ReceiverMoneyStorage->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Additional !== null) {
            $xfer += $output->writeFieldBegin('Additional', TType::STRING, 10);
            $xfer += $output->writeString($this->Additional);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocumentSumm !== null) {
            $xfer += $output->writeFieldBegin('DocumentSumm', TType::DOUBLE, 11);
            $xfer += $output->writeDouble($this->DocumentSumm);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->GUID !== null) {
            $xfer += $output->writeFieldBegin('GUID', TType::STRING, 12);
            $xfer += $output->writeString($this->GUID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocNumber !== null) {
            $xfer += $output->writeFieldBegin('DocNumber', TType::STRING, 13);
            $xfer += $output->writeString($this->DocNumber);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocumentDate !== null) {
            $xfer += $output->writeFieldBegin('DocumentDate', TType::STRING, 14);
            $xfer += $output->writeString($this->DocumentDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterCodes !== null) {
            if (!is_array($this->OuterCodes)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('OuterCodes', TType::LST, 15);
            $output->writeListBegin(TType::STRUCT, count($this->OuterCodes));
            foreach ($this->OuterCodes as $iter909) {
                $xfer += $iter909->write($output);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        if ($this->StateMoney !== null) {
            $xfer += $output->writeFieldBegin('StateMoney', TType::STRING, 16);
            $xfer += $output->writeString($this->StateMoney);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
