<?php
namespace Workabox\API;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class ProductionOperationsFilter
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'ID',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'OuterID',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'Additional',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'DocumentSumm',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'Responsible',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        6 => array(
            'var' => 'StoreMaterials',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        7 => array(
            'var' => 'Routings',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        8 => array(
            'var' => 'ProdVolume',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        9 => array(
            'var' => 'ProdCost',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        10 => array(
            'var' => 'StoreFinished',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\Workabox\API\ObjectID',
        ),
        11 => array(
            'var' => 'DocNumber',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        12 => array(
            'var' => 'DocumentDate',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        13 => array(
            'var' => 'StateDocuments',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var int
     */
    public $ID = null;
    /**
     * @var string
     */
    public $OuterID = null;
    /**
     * @var string
     */
    public $Additional = null;
    /**
     * @var string
     */
    public $DocumentSumm = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $Responsible = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $StoreMaterials = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $Routings = null;
    /**
     * @var string
     */
    public $ProdVolume = null;
    /**
     * @var string
     */
    public $ProdCost = null;
    /**
     * @var \Workabox\API\ObjectID
     */
    public $StoreFinished = null;
    /**
     * @var string
     */
    public $DocNumber = null;
    /**
     * @var string
     */
    public $DocumentDate = null;
    /**
     * @var string[]
     */
    public $StateDocuments = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['ID'])) {
                $this->ID = $vals['ID'];
            }
            if (isset($vals['OuterID'])) {
                $this->OuterID = $vals['OuterID'];
            }
            if (isset($vals['Additional'])) {
                $this->Additional = $vals['Additional'];
            }
            if (isset($vals['DocumentSumm'])) {
                $this->DocumentSumm = $vals['DocumentSumm'];
            }
            if (isset($vals['Responsible'])) {
                $this->Responsible = $vals['Responsible'];
            }
            if (isset($vals['StoreMaterials'])) {
                $this->StoreMaterials = $vals['StoreMaterials'];
            }
            if (isset($vals['Routings'])) {
                $this->Routings = $vals['Routings'];
            }
            if (isset($vals['ProdVolume'])) {
                $this->ProdVolume = $vals['ProdVolume'];
            }
            if (isset($vals['ProdCost'])) {
                $this->ProdCost = $vals['ProdCost'];
            }
            if (isset($vals['StoreFinished'])) {
                $this->StoreFinished = $vals['StoreFinished'];
            }
            if (isset($vals['DocNumber'])) {
                $this->DocNumber = $vals['DocNumber'];
            }
            if (isset($vals['DocumentDate'])) {
                $this->DocumentDate = $vals['DocumentDate'];
            }
            if (isset($vals['StateDocuments'])) {
                $this->StateDocuments = $vals['StateDocuments'];
            }
        }
    }

    public function getName()
    {
        return 'ProductionOperationsFilter';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->ID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->OuterID);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->Additional);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocumentSumm);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRUCT) {
                        $this->Responsible = new \Workabox\API\ObjectID();
                        $xfer += $this->Responsible->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::STRUCT) {
                        $this->StoreMaterials = new \Workabox\API\ObjectID();
                        $xfer += $this->StoreMaterials->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 7:
                    if ($ftype == TType::STRUCT) {
                        $this->Routings = new \Workabox\API\ObjectID();
                        $xfer += $this->Routings->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 8:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ProdVolume);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 9:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->ProdCost);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 10:
                    if ($ftype == TType::STRUCT) {
                        $this->StoreFinished = new \Workabox\API\ObjectID();
                        $xfer += $this->StoreFinished->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 11:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocNumber);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 12:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->DocumentDate);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 13:
                    if ($ftype == TType::LST) {
                        $this->StateDocuments = array();
                        $_size966 = 0;
                        $_etype969 = 0;
                        $xfer += $input->readListBegin($_etype969, $_size966);
                        for ($_i970 = 0; $_i970 < $_size966; ++$_i970) {
                            $elem971 = null;
                            $xfer += $input->readString($elem971);
                            $this->StateDocuments []= $elem971;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ProductionOperationsFilter');
        if ($this->ID !== null) {
            $xfer += $output->writeFieldBegin('ID', TType::I32, 1);
            $xfer += $output->writeI32($this->ID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->OuterID !== null) {
            $xfer += $output->writeFieldBegin('OuterID', TType::STRING, 2);
            $xfer += $output->writeString($this->OuterID);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Additional !== null) {
            $xfer += $output->writeFieldBegin('Additional', TType::STRING, 3);
            $xfer += $output->writeString($this->Additional);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocumentSumm !== null) {
            $xfer += $output->writeFieldBegin('DocumentSumm', TType::STRING, 4);
            $xfer += $output->writeString($this->DocumentSumm);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Responsible !== null) {
            if (!is_object($this->Responsible)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Responsible', TType::STRUCT, 5);
            $xfer += $this->Responsible->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->StoreMaterials !== null) {
            if (!is_object($this->StoreMaterials)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('StoreMaterials', TType::STRUCT, 6);
            $xfer += $this->StoreMaterials->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->Routings !== null) {
            if (!is_object($this->Routings)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('Routings', TType::STRUCT, 7);
            $xfer += $this->Routings->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ProdVolume !== null) {
            $xfer += $output->writeFieldBegin('ProdVolume', TType::STRING, 8);
            $xfer += $output->writeString($this->ProdVolume);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->ProdCost !== null) {
            $xfer += $output->writeFieldBegin('ProdCost', TType::STRING, 9);
            $xfer += $output->writeString($this->ProdCost);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->StoreFinished !== null) {
            if (!is_object($this->StoreFinished)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('StoreFinished', TType::STRUCT, 10);
            $xfer += $this->StoreFinished->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocNumber !== null) {
            $xfer += $output->writeFieldBegin('DocNumber', TType::STRING, 11);
            $xfer += $output->writeString($this->DocNumber);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->DocumentDate !== null) {
            $xfer += $output->writeFieldBegin('DocumentDate', TType::STRING, 12);
            $xfer += $output->writeString($this->DocumentDate);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->StateDocuments !== null) {
            if (!is_array($this->StateDocuments)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('StateDocuments', TType::LST, 13);
            $output->writeListBegin(TType::STRING, count($this->StateDocuments));
            foreach ($this->StateDocuments as $iter972) {
                $xfer += $output->writeString($iter972);
            }
            $output->writeListEnd();
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
